name: Python Greetings Pipeline

on:
  workflow_dispatch:

jobs:
  install-pip-deps:
    runs-on: self-hosted

    steps:
      - name: Checkout pipeline repo
        uses: actions/checkout@v4

      - name: Run install composite action
        uses: ./.github/actions/install-python-deps
        with:
          app_path: python-greetings

  deploy-to-dev:
    runs-on: self-hosted
    needs: install-pip-deps

    steps:
      - name: Checkout pipeline repo
        uses: actions/checkout@v4

      - name: Clone python app
        uses: actions/checkout@v4
        with:
          repository: mtararujs/python-greetings
          path: python-greetings

      - name: Stop old app (if exists)
        run: pm2 delete greetings-dev || true

      - name: Create virtual environment
        run: python3 -m venv venv
        working-directory: python-greetings

      - name: Install requirements
        run: ./venv/bin/python -m pip install -r requirements.txt
        working-directory: python-greetings

      - name: Start app on port 7001
        run: |
          pm2 start "./venv/bin/python app.py --port=7001" --name greetings-dev
          pm2 save
        working-directory: python-greetings

  tests-on-dev:
    runs-on: self-hosted
    needs: deploy-to-dev

    steps:
      - name: Checkout pipeline repo
        uses: actions/checkout@v4

      - name: Clone test repo
        uses: actions/checkout@v4
        with:
          repository: mtararujs/course-js-api-framework
          path: tests

      - name: Install npm dependencies
        run: npm install
        working-directory: tests

      - name: Run tests on dev
        run: npm run greetings greetings_dev
        working-directory: tests

  deploy-to-stg:
    runs-on: self-hosted
    needs: tests-on-dev

    steps:
      - name: Checkout pipeline repo
        uses: actions/checkout@v4

      - name: Clone python app
        uses: actions/checkout@v4
        with:
          repository: mtararujs/python-greetings
          path: python-greetings

      - name: Stop old app
        run: pm2 delete greetings-stg || true

      - name: Create virtual environment
        run: python3 -m venv venv
        working-directory: python-greetings

      - name: Install requirements
        run: ./venv/bin/python -m pip install -r requirements.txt
        working-directory: python-greetings

      - name: Start app on port 7002
        run: |
          pm2 start "./venv/bin/python app.py --port=7002" --name greetings-stg
          pm2 save
        working-directory: python-greetings

  tests-on-stg:
    runs-on: self-hosted
    needs: deploy-to-stg

    steps:
      - name: Checkout pipeline repo
        uses: actions/checkout@v4

      - name: Clone test repo
        uses: actions/checkout@v4
        with:
          repository: mtararujs/course-js-api-framework
          path: tests

      - name: Install npm dependencies
        run: npm install
        working-directory: tests

      - name: Run tests on stg
        run: npm run greetings greetings_stg
        working-directory: tests

  deploy-to-preprod:
    runs-on: self-hosted
    needs: tests-on-stg

    steps:
      - name: Checkout pipeline repo
        uses: actions/checkout@v4

      - name: Clone python app
        uses: actions/checkout@v4
        with:
          repository: mtararujs/python-greetings
          path: python-greetings

      - name: Stop old app
        run: pm2 delete greetings-preprod || true

      - name: Create virtual environment
        run: python3 -m venv venv
        working-directory: python-greetings

      - name: Install requirements
        run: ./venv/bin/python -m pip install -r requirements.txt
        working-directory: python-greetings

      - name: Start app on port 7003
        run: |
          pm2 start "./venv/bin/python app.py --port=7003" --name greetings-preprod
          pm2 save
        working-directory: python-greetings

  tests-on-preprod:
    runs-on: self-hosted
    needs: deploy-to-preprod

    steps:
      - name: Checkout pipeline repo
        uses: actions/checkout@v4

      - name: Clone test repo
        uses: actions/checkout@v4
        with:
          repository: mtararujs/course-js-api-framework
          path: tests

      - name: Install npm dependencies
        run: npm install
        working-directory: tests

      - name: Run tests on preprod
        run: npm run greetings greetings_preprod
        working-directory: tests

  deploy-to-prod:
    runs-on: self-hosted
    needs: tests-on-preprod

    steps:
      - name: Checkout pipeline repo
        uses: actions/checkout@v4

      - name: Clone python app
        uses: actions/checkout@v4
        with:
          repository: mtararujs/python-greetings
          path: python-greetings

      - name: Stop old app
        run: pm2 delete greetings-prod || true

      - name: Create virtual environment
        run: python3 -m venv venv
        working-directory: python-greetings

      - name: Install requirements
        run: ./venv/bin/python -m pip install -r requirements.txt
        working-directory: python-greetings

      - name: Start app on port 7004
        run: |
          pm2 start "./venv/bin/python app.py --port=7004" --name greetings-prod
          pm2 save
        working-directory: python-greetings

  tests-on-prod:
    runs-on: self-hosted
    needs: deploy-to-prod

    steps:
      - name: Checkout pipeline repo
        uses: actions/checkout@v4

      - name: Clone test repo
        uses: actions/checkout@v4
        with:
          repository: mtararujs/course-js-api-framework
          path: tests

      - name: Install npm dependencies
        run: npm install
        working-directory: tests

      - name: Run tests on prod
        run: npm run greetings greetings_prod
        working-directory: tests
